version: '3.9'

services: # Here we define our service(s)
    angular-service: # The name of the service
      container_name: angularcontainer  # Container name
      build: ./Dockerfile # Location of our Dockerfile
      volumes: # Volume binding
        - './angulardockerproject:/usr/src/app'
      ports:
        - '4200:4200' # Port mapping
      command: >
        bash -c "npm install && ng serve --host 0.0.0.0 --port 4200"

  mariadb:
    image: mariadb
    ports:
      - 3306:3306
    volumes:
      - ~/apps/mariadb:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=nimda
      - MYSQL_PASSWORD=1234
      - MYSQL_USER=cy09
      - MYSQL_DATABASE=dnddb
